// <auto-generated />
using System;
using AkkaDistribution.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkkaDistribution.Server.Data.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20230305210954_AddFilePartDeliveries")]
    partial class AddFilePartDeliveries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("AkkaDistribution.Server.Data.FilePartDelivery", b =>
                {
                    b.Property<int>("FilePartDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPieces")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilePartDeliveryId");

                    b.ToTable("FilePartDeliveries");
                });

            modelBuilder.Entity("AkkaDistribution.Server.Data.Manifest", b =>
                {
                    b.Property<int>("ManifestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ManifestId");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("AkkaDistribution.Server.Data.ManifestEntry", b =>
                {
                    b.Property<int>("ManifestEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ManifestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ManifestEntryId");

                    b.HasIndex("ManifestId");

                    b.ToTable("ManifestEntries");
                });

            modelBuilder.Entity("AkkaDistribution.Server.Data.ManifestEntry", b =>
                {
                    b.HasOne("AkkaDistribution.Server.Data.Manifest", null)
                        .WithMany("ManifestEntries")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AkkaDistribution.Server.Data.Manifest", b =>
                {
                    b.Navigation("ManifestEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
